workspace:
  base: /go
  path: src/golang.scot/project

pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go get -u golang.org/x/vgo
      - cd liberty && vgo test ./...  && vgo build .

  publish-latest:
    image: plugins/docker
    repo: registry.golang.scot/liberty
    registry: registry.golang.scot
    dockerfile: liberty/Dockerfile
    secrets: [ docker_username, docker_password ]
    tags: latest

  publish-tags:
    image: plugins/docker
    repo: registry.golang.scot/liberty
    registry: registry.golang.scot
    dockerfile: liberty/Dockerfile
    secrets: [ docker_username, docker_password ]
    tags: "${DRONE_TAG##v}"
    when:
        event: tag

matrix:
  GO_VERSION:
    - 1.10.2
    - 1.10.3
