workspace:
  base: /go
  path: src/golang.scot/project

pipeline:
  tests:
    image: golang:${GO_VERSION}
    commands:
      - go get -u golang.org/x/vgo
      - cd liberty && vgo test ./...  && vgo build .

  docker-liberty:
    image: plugins/docker
    repo: registry.golang.scot/liberty
    dockerfile: liberty/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
        event: tag
        branch: master

matrix:
  GO_VERSION:
    - 1.10.2
    - 1.10.3
